#include "qwcursor.h"
#include "qwbuffer.h"
#include "qwinputdevice.h"
#include "qwcompositor.h"
#include "qwoutputlayout.h"
#include "qwoutput.h"
#include "qwxcursormanager.h"
#include "private/qwglobal_p.h"
#include <QImage>
#include <QPointF>
#include <QHash>
extern "C" {
#include <math.h>
#define static
#include <wlr/types/wlr_cursor.h>
#undef static
#include <wlr/util/box.h>
QW_SIGNAL(motion, arguments?)
QW_SIGNAL(motion_absolute, arguments?)
QW_SIGNAL(button, arguments?)
QW_SIGNAL(axis, arguments?)
QW_SIGNAL(frame, arguments?)
QW_SIGNAL(swipe_begin, arguments?)
QW_SIGNAL(swipe_update, arguments?)
QW_SIGNAL(swipe_end, arguments?)
QW_SIGNAL(pinch_begin, arguments?)
QW_SIGNAL(pinch_update, arguments?)
QW_SIGNAL(pinch_end, arguments?)
QW_SIGNAL(hold_begin, arguments?)
QW_SIGNAL(hold_end, arguments?)
QW_SIGNAL(touch_up, arguments?)
QW_SIGNAL(touch_down, arguments?)
QW_SIGNAL(touch_motion, arguments?)
QW_SIGNAL(touch_cancel, arguments?)
QW_SIGNAL(touch_frame, arguments?)
QW_SIGNAL(tablet_tool_axis, arguments?)
QW_SIGNAL(tablet_tool_proximity, arguments?)
QW_SIGNAL(tablet_tool_tip, arguments?)
QW_SIGNAL(tablet_tool_button, arguments?)
QW_FUNC_MEMBER(cursor, create)
QW_FUNC_MEMBER(cursor, warp)
QW_FUNC_MEMBER(cursor, warp_closest)
QW_FUNC_MEMBER(cursor, warp_absolute)
QW_FUNC_MEMBER(cursor, move)
QW_FUNC_MEMBER(cursor, set_buffer)
QW_FUNC_MEMBER(cursor, set_xcursor)
QW_FUNC_MEMBER(cursor, unset_image)
QW_FUNC_MEMBER(cursor, set_surface)
QW_FUNC_MEMBER(cursor, attach_input_device)
QW_FUNC_MEMBER(cursor, detach_input_device)
QW_FUNC_MEMBER(cursor, attach_output_layout)
QW_FUNC_MEMBER(cursor, map_to_output)
QW_FUNC_MEMBER(cursor, map_input_to_output)
QW_FUNC_MEMBER(cursor, map_to_region)
QW_FUNC_MEMBER(cursor, map_input_to_region)
QW_FUNC_MEMBER(cursor, absolute_to_layout_coords)
