#include "qwscene.h"
#include "qwoutputlayout.h"
#include "qwbuffer.h"
#include "qwxdgshell.h"
#include "qwlayershellv1.h"
#include "qwoutput.h"
#include "qwcompositor.h"
#include "private/qwglobal_p.h"
#include <QColor>
#include <QPoint>
#include <QRect>
#include <QHash>
extern "C" {
#include <math.h>
#define static
#include <wlr/types/wlr_scene.h>
#undef static
#include <wlr/util/box.h>
QW_FUNC_MEMBER(scene, node_set_enabled)
QW_FUNC_MEMBER(scene, node_set_position)
QW_FUNC_MEMBER(scene, node_place_above)
QW_FUNC_MEMBER(scene, node_place_below)
QW_FUNC_MEMBER(scene, node_raise_to_top)
QW_FUNC_MEMBER(scene, node_lower_to_bottom)
QW_FUNC_MEMBER(scene, node_reparent)
QW_FUNC_MEMBER(scene, node_coords)
QW_FUNC_MEMBER(scene, node_for_each_buffer)
QW_FUNC_MEMBER(scene, node_at)
QW_FUNC_MEMBER(scene, tree_create)
QW_FUNC_MEMBER(scene, subsurface_tree_create)
QW_FUNC_MEMBER(scene, xdg_surface_create)
QW_FUNC_MEMBER(scene, create)
#if WLR_VERSION_MINOR < 18
QW_FUNC_MEMBER(scene, set_presentation)
#endif
QW_FUNC_MEMBER(scene, attach_output_layout)
QW_SIGNAL(output_enter, arguments?)
QW_SIGNAL(output_leave, arguments?)
QW_SIGNAL(output_sample, arguments?)
QW_SIGNAL(frame_done, arguments?)
QW_FUNC_MEMBER(scene, buffer_create)
QW_FUNC_MEMBER(scene, buffer_from_node)
QW_FUNC_MEMBER(scene, buffer_from_node)
QW_FUNC_MEMBER(scene, buffer_set_buffer)
QW_FUNC_MEMBER(scene, buffer_set_buffer_with_damage)
QW_FUNC_MEMBER(scene, buffer_set_opaque_region)
QW_FUNC_MEMBER(scene, buffer_set_source_box)
QW_FUNC_MEMBER(scene, buffer_set_dest_size)
QW_FUNC_MEMBER(scene, buffer_set_transform)
QW_FUNC_MEMBER(scene, buffer_send_frame_done)
QW_FUNC_MEMBER(scene, rect_create)
QW_FUNC_MEMBER(scene, rect_set_size)
QW_FUNC_MEMBER(scene, rect_set_color)
QW_FUNC_MEMBER(scene, output_create)
QW_FUNC_MEMBER(scene, get_scene_output)
QW_FUNC_MEMBER(scene, output_commit)
QW_FUNC_MEMBER(scene, output_send_frame_done)
QW_FUNC_MEMBER(scene, output_for_each_buffer)
