#include "qwxwaylandsurface.h"
#include "qwcompositor.h"
#include "private/qwglobal_p.h"
#include <QRect>
#include <QHash>
extern "C" {
#include <xcb/xproto.h>
#include <math.h>
#define class _class
#include <wlr/xwayland/xwayland.h>
#undef class
QW_SIGNAL(request_configure, arguments?)
QW_SIGNAL(request_move, arguments?)
QW_SIGNAL(request_resize, arguments?)
QW_SIGNAL(request_minimize, arguments?)
QW_SIGNAL(request_maximize, arguments?)
QW_SIGNAL(request_fullscreen, arguments?)
QW_SIGNAL(request_activate, arguments?)
QW_SIGNAL(associate, arguments?)
QW_SIGNAL(dissociate, arguments?)
QW_SIGNAL(set_strut_partial, arguments?)
QW_SIGNAL(set_title, arguments?)
QW_SIGNAL(set_class, arguments?)
QW_SIGNAL(set_role, arguments?)
QW_SIGNAL(set_parent, arguments?)
QW_SIGNAL(set_startup_id, arguments?)
QW_SIGNAL(set_window_type, arguments?)
QW_SIGNAL(set_hints, arguments?)
QW_SIGNAL(set_decorations, arguments?)
QW_SIGNAL(set_override_redirect, arguments?)
QW_SIGNAL(set_geometry, arguments?)
QW_SIGNAL(ping_timeout, arguments?)
QW_FUNC_MEMBER(xwayland, surface_activate)
QW_FUNC_MEMBER(xwayland, surface_restack)
QW_FUNC_MEMBER(xwayland, surface_configure)
QW_FUNC_MEMBER(xwayland, surface_close)
QW_FUNC_MEMBER(xwayland, surface_set_withdrawn)
QW_FUNC_MEMBER(xwayland, surface_set_minimized)
QW_FUNC_MEMBER(xwayland, surface_set_maximized)
QW_FUNC_MEMBER(xwayland, surface_set_fullscreen)
QW_FUNC_MEMBER(xwayland, surface_try_from_wlr_surface)
QW_FUNC_MEMBER(xwayland, surface_ping)
QW_FUNC_MEMBER(xwayland, or_surface_wants_focus)
QW_FUNC_MEMBER(xwayland, icccm_input_model)
